// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9-3UGQ6zbh3JywndoHv3lHnil7uYQRwE',
    appId: '1:459899359880:web:25e91958c3efe8db13c53d',
    messagingSenderId: '459899359880',
    projectId: 'ca-mobile-47ca9',
    authDomain: 'ca-mobile-47ca9.firebaseapp.com',
    storageBucket: 'ca-mobile-47ca9.appspot.com',
    measurementId: 'G-CNSD74S113',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATwwW6bJZ0XYu37WPadxPnHF80hbz2PRQ',
    appId: '1:459899359880:android:b9404f59faea5ca913c53d',
    messagingSenderId: '459899359880',
    projectId: 'ca-mobile-47ca9',
    storageBucket: 'ca-mobile-47ca9.appspot.com',
  );
}
